name: Code Analysis

on:
    push:
        branches-ignore:
            - gh-pages
    pull_request:
        branches-ignore:
            - gh-pages

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.11

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install pylint flake8

            -   name: Run pylint
                run: |
                    pylint notion_apilib

            -   name: Run flake8
                run: |
                    flake8 notion_apilib
