name: Generate Doxygen Documentation

permissions:
    contents: write

on:
    push:
        branches:
            - main

jobs:
    generate-docs:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            -   name: Set up Doxygen
                run: sudo apt-get install -y doxygen graphviz

            -   name: Generate Doxygen Documentation
                run: doxygen Doxyfile

            -   name: Move HTML Documentation to docs/
                run: |
                    mv docs/html/* docs/
                    rm -rf docs/html

            -   name: Deploy Documentation to GitHub Pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./docs
                    keep_files: true
