name: Testing

on:
    push:
        branches-ignore:
            - gh-pages
    pull_request:
        branches-ignore:
            - gh-pages

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up Python 3.9
                uses: actions/setup-python@v4
                with:
                    python-version: 3.9

            -   name: Install Poetry
                run: |
                    curl -sSL https://install.python-poetry.org | python3 -
                    echo "$HOME/.local/bin" >> $GITHUB_PATH

            -   name: Update Poetry lock file
                run: |
                    poetry lock --no-update

            -   name: Install dependencies with Poetry
                run: |
                    poetry install

            -   name: Run tests
                run: |
                    poetry run pytest --ignore=tests/marked_tests/
